
# storage system will be initialized with this name
storage: 
    name: zk
    options:
        zk:
            url: 192.168.8.3:2182,192.168.8.3:2183,192.168.8.3:2184
            options:
                sessionTimeout: 10000
        poolroot: /TEST_MICRO/services
        treeroot: /TEST_MICRO/apps
# server configurations
server:
    port: 20001
loadbalance: P2cBalancer
# log configurations
log:
    appenders:
        console:
            type: console
    categories: 
        default: 
            appenders: 
                - console
            level: debug
# system paths
path:
    controller: ./src/controller
    router: ./src/router